version: '3.1'

services:
  db:
    container_name: CasinoWinnerDatabase
    image: postgres
    restart: always
    ports:
      - 8011:5432
    environment:
      POSTGRES_USER: casinoadmin
      POSTGRES_PASSWORD: casinopass
      POSTGRES_DB: casino
  redis:
    container_name: CasinoWinnerRedis
    image: redis
    ports:
      - 8012:6379
